### ISSUE TITLE
Convert json to graphl schema ?

### ISSUE THREAD

**Issue by anuraggo** [charlypoly/graphql-to-json-schema#37]
Hi @charlypoly 

I want to convert back the JSON schema(generated using 'graphql-to-json-schema') to GraphQL schema.
Do we have any such method or way to do it ?

Please let me know.
Any kind of help is appreciated.

Thanks,
Anurag

**Comment by charlypoly** [comment]
Hi @anuraggo 

Unfortunately, there is no such method for now.
I might need a JSON Schema to GraphQL soon, so I might create a `json-schema-to-graphql` repo.

I the meantime, you can try the following repo: [jsonschema-to-graphql](https://www.npmjs.com/package/jsonschema-to-graphql)

**Comment by charlypoly** [comment]
Hi @anuraggo 👋🏼 

I just published [json-schema-to-graphql](https://github.com/charlypoly/json-schema-to-graphql) ✨ 

Best,

**Comment by anuraggo** [comment]
Thanks :-)
