### ISSUE TITLE
Default values for complex object types

### ISSUE THREAD

**Issue by jcuna** [charlypoly/graphql-to-json-schema#67]
I'm experiencing an issue that arises from having default values for complex object types (non scalar). For example, the following syntax is a valid graphql syntax.
~~~gql
input SectionAttributesInput {
  render_on_page: Boolean = true
}

input NewSectionInput {
  archived: Boolean
  attributes: SectionAttributesInput = {render_on_page: true}
  ...
}
~~~
however, `graphql-2-json-schema.fromIntrospectionQuery`,  is unable to parse it with an error in the likes of `SyntaxError: Unexpected token r in JSON at position 1`
The culprit being:
```
{render_on_page: true}
 ^
```

**Comment by newhouse** [comment]
Fix is here: https://github.com/charlypoly/graphql-to-json-schema/pull/69
